// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOIq-D9c-XlEjWyPQNID50Ork_pd5n7Q',
    appId: '1:648773336207:web:913e849e2713703e32c4fa',
    messagingSenderId: '648773336207',
    projectId: 'totp-auth-website',
    authDomain: 'totp-auth-website.firebaseapp.com',
    storageBucket: 'totp-auth-website.appspot.com',
    measurementId: 'G-LQMMYXX0PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbd22AwKDCDYzwoZWfNSNcaSHHflKURM',
    appId: '1:648773336207:android:5a35fd64851fecfd32c4fa',
    messagingSenderId: '648773336207',
    projectId: 'totp-auth-website',
    storageBucket: 'totp-auth-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsOh0RwdmTETwUhATQLJzl6AerUcL_y8A',
    appId: '1:648773336207:ios:0147b67aa61bdb0532c4fa',
    messagingSenderId: '648773336207',
    projectId: 'totp-auth-website',
    storageBucket: 'totp-auth-website.appspot.com',
    androidClientId: '648773336207-mhtcnfu9iqsco2gev5ale6pi07sbr7ug.apps.googleusercontent.com',
    iosClientId: '648773336207-cs9erjrg3bacsl1tbk87g22akfqk2c0q.apps.googleusercontent.com',
    iosBundleId: 'com.bityo.securibit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsOh0RwdmTETwUhATQLJzl6AerUcL_y8A',
    appId: '1:648773336207:ios:4fd257c3f0355a7832c4fa',
    messagingSenderId: '648773336207',
    projectId: 'totp-auth-website',
    storageBucket: 'totp-auth-website.appspot.com',
    androidClientId: '648773336207-mhtcnfu9iqsco2gev5ale6pi07sbr7ug.apps.googleusercontent.com',
    iosClientId: '648773336207-rn21jd1q8cbdm3tgftjhv4rp4a964p9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.securibit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWaxVeKFmruMYmckjLszxA4m9Dm9_Z3v8',
    appId: '1:648773336207:web:b6f72fcb43381c2932c4fa',
    messagingSenderId: '648773336207',
    projectId: 'totp-auth-website',
    authDomain: 'totp-auth-website.firebaseapp.com',
    storageBucket: 'totp-auth-website.appspot.com',
    measurementId: 'G-K4F68L43RX',
  );
}
